name:                http-proxy-lambda
version:             0.1.0
github:              "githubuser/http-proxy-lambda"
license:             BSD3
author:              "Christopher Grounds"
copyright:           "2019 Christopher Grounds"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- serverless-haskell
- aeson
- lens
- text
- bytestring
- unordered-containers
- wreq

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  proxy:
    main:        Proxy.hs
    source-dirs: app
    ghc-options:
    - -main-is Proxy.mainHandler
